apiVersion: v1
kind: Service
metadata:
  name: cloudedu-service
  namespace: cloudedu-services
  labels:
    app: cloudedu-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: cloudedu-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: cloudedu-service-internal
  namespace: cloudedu-services
  labels:
    app: cloudedu-app
spec:
  type: ClusterIP
  selector:
    app: cloudedu-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
